### ISSUE TITLE
can not find expiring order, happened once, need to reproduce

### ISSUE THREAD

**Issue by helinwang** [helinwang/dex#33]
```
panic: can not find expiring order

goroutine 37749 [running]:
github.com/helinwang/dex/pkg/dex.(*Transition).expireOrders(0xc420594960)
	/home/helin/env/gopath/src/github.com/helinwang/dex/pkg/dex/transition.go:609 +0x443
github.com/helinwang/dex/pkg/dex.(*Transition).finalizeState(0xc420594960)
	/home/helin/env/gopath/src/github.com/helinwang/dex/pkg/dex/transition.go:509 +0x6b
github.com/helinwang/dex/pkg/dex.(*Transition).Txns(0xc420594960, 0x20, 0x20, 0xc422648000)
	/home/helin/env/gopath/src/github.com/helinwang/dex/pkg/dex/transition.go:447 +0x2f
github.com/helinwang/dex/pkg/consensus.(*Chain).ProposeBlock(0xc4200f07e0, 0x90c360, 0xc4208050e0, 0xc4201d6620, 0x20, 0x20, 0x2ef, 0xc420668a00)
	/home/helin/env/gopath/src/github.com/helinwang/dex/pkg/consensus/chain.go:185 +0x44a
github.com/helinwang/dex/pkg/consensus.(*Node).proposeBlock(0xc42001f130, 0x2ef, 0x2, 0xbec61965fb7edf53, 0xb06c6bb8bc, 0xd21c00)
	/home/helin/env/gopath/src/github.com/helinwang/dex/pkg/consensus/node.go:109 +0x3b2
created by github.com/helinwang/dex/pkg/consensus.(*Node).StartRound
	/home/helin/env/gopath/src/github.com/helinwang/dex/pkg/consensus/node.go:161 +0x9a6
```

**Comment by helinwang** [comment]
Need to look into it more, I replaced the panic with a error message.
